version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.10-apache-stretch-node-browsers
    working_directory: ~/matryoshka-server

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install composer dependencies
          command: composer install -n --prefer-dist

      - run:
          name: Install Node.js dependencies
          command: npm install

      - save_cache:
          paths:
            - ./vendor
            - ./node_modules
          key: v1-dependencies-{{ checksum "composer.json" }}-{{ checksum "package.json" }}

      - run:
          name: Use testing environment
          command: cp .env.testing .env

      - run:
          name: Install application
          command: php artisan app:install

      - run:
          name: Run PHPUnit tests
          command: ./vendor/bin/phpunit

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1d:fe:e6:ec:53:51:ca:98:38:85:1e:d7:6a:98:6f:dc"

      - run:
          name: Deploy via SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./deploy.sh"

workflows:
  version: 2
  primary:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
