# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.10-apache-stretch-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/matryoshka-server

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install composer dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Use testing environment
          command: cp .env.testing .env

      - run:
          name: Install application
          command: php artisan app:install

  test:
    docker:
      - image: circleci/php:7.2.10-apache-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: Run PHPUnit tests
          command: ./vendor/bin/phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
